# Generated by Django 5.0.6 on 2024-10-06 09:38

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_faculty_image_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='org_chart'),
        ),
    ]
